<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;
use Carbon\Carbon;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            [
                'name' => 'Paracetamol 500mg',
                'category_id' => 1,
                'brand' => 'PharmaBrand',
                'manufacturer' => 'PharmaCo',
                'image' => 'products/paracetamol.jpg',
                'images' => json_encode(['products/paracetamol.jpg','products/paracetamol2.jpg']),
                'price' => 2.50,
                'discount' => 0,
                'stock' => 100,
                'availability' => 'in stock',
                'isNew' => true,
                'requiresPrescription' => false,
                'dosageForm' => 'Tablet',
                'strength' => '500mg',
                'ingredients' => 'Paracetamol',
                'usage' => 'Take 1 tablet every 6 hours',
                'expiryDate' => Carbon::now()->addYear(),
                'sideEffects' => 'Nausea, dizziness',
                'warning' => 'Do not exceed recommended dose',
                'storage' => 'Store in a cool, dry place',
                'rating' => 4.5,
                'reviews' => 10,
                'reviewsList' => json_encode([
                    ['user'=>'Client1','review'=>'Very effective'],
                    ['user'=>'Client2','review'=>'Good value']
                ]),
                'barcode' => '1234567890123',
                'batch_number' => 'BATCH001',
                'description' => 'Pain relief for headaches and fever'
            ],
            [
                'name' => 'Ibuprofen 200mg',
                'category_id' => 1,
                'brand' => 'PharmaBrand',
                'manufacturer' => 'PharmaCo',
                'image' => 'products/ibuprofen.jpg',
                'images' => json_encode(['products/ibuprofen.jpg']),
                'price' => 3.00,
                'discount' => 0,
                'stock' => 80,
                'availability' => 'in stock',
                'isNew' => false,
                'requiresPrescription' => false,
                'dosageForm' => 'Tablet',
                'strength' => '200mg',
                'ingredients' => 'Ibuprofen',
                'usage' => 'Take 1 tablet every 8 hours',
                'expiryDate' => Carbon::now()->addYear(),
                'sideEffects' => 'Upset stomach, dizziness',
                'warning' => 'Take with food',
                'storage' => 'Store at room temperature',
                'rating' => 4.2,
                'reviews' => 5,
                'reviewsList' => json_encode([]),
                'barcode' => '1234567890456',
                'batch_number' => 'BATCH002',
                'description' => 'Reduces pain, fever and inflammation'
            ],
            [
                'name' => 'Vitamin C 500mg',
                'category_id' => 3,
                'brand' => 'HealthPlus',
                'manufacturer' => 'VitaCo',
                'image' => 'products/vitamin_c.jpg',
                'images' => json_encode(['products/vitamin_c.jpg']),
                'price' => 5.00,
                'discount' => 0,
                'stock' => 200,
                'availability' => 'in stock',
                'isNew' => true,
                'requiresPrescription' => false,
                'dosageForm' => 'Tablet',
                'strength' => '500mg',
                'ingredients' => 'Vitamin C',
                'usage' => 'Take 1 tablet daily',
                'expiryDate' => Carbon::now()->addYears(2),
                'sideEffects' => 'Rare: stomach upset',
                'warning' => 'Do not exceed daily dose',
                'storage' => 'Keep away from sunlight',
                'rating' => 4.8,
                'reviews' => 15,
                'reviewsList' => json_encode([]),
                'barcode' => '1234567890789',
                'batch_number' => 'BATCH003',
                'description' => 'Supports immune system'
            ],
            [
                'name' => 'Antibiotic Cream',
                'category_id' => 4,
                'brand' => 'MedSkin',
                'manufacturer' => 'SkinPharma',
                'image' => 'products/antibiotic_cream.jpg',
                'images' => json_encode(['products/antibiotic_cream.jpg']),
                'price' => 6.50,
                'discount' => 0,
                'stock' => 50,
                'availability' => 'in stock',
                'isNew' => false,
                'requiresPrescription' => true,
                'dosageForm' => 'Cream',
                'strength' => '5%',
                'ingredients' => 'Antibiotic mix',
                'usage' => 'Apply twice daily',
                'expiryDate' => Carbon::now()->addYear(),
                'sideEffects' => 'Mild irritation',
                'warning' => 'Prescription required',
                'storage' => 'Store below 25°C',
                'rating' => 4.0,
                'reviews' => 8,
                'reviewsList' => json_encode([]),
                'barcode' => '1234567890999',
                'batch_number' => 'BATCH004',
                'description' => 'For skin infections'
            ],
            [
                'name' => 'Baby Lotion',
                'category_id' => 5,
                'brand' => 'BabyCare',
                'manufacturer' => 'KidsPharma',
                'image' => 'products/baby_lotion.jpg',
                'images' => json_encode(['products/baby_lotion.jpg']),
                'price' => 4.00,
                'discount' => 0,
                'stock' => 60,
                'availability' => 'in stock',
                'isNew' => true,
                'requiresPrescription' => false,
                'dosageForm' => 'Lotion',
                'strength' => null,
                'ingredients' => 'Moisturizers',
                'usage' => 'Apply on skin',
                'expiryDate' => Carbon::now()->addYears(2),
                'sideEffects' => 'None',
                'warning' => 'External use only',
                'storage' => 'Store at room temperature',
                'rating' => 4.3,
                'reviews' => 6,
                'reviewsList' => json_encode([]),
                'barcode' => '1234567891111',
                'batch_number' => 'BATCH005',
                'description' => 'Keeps baby skin soft'
            ],
            [
                'name' => 'Allergy Relief Tablets',
                'category_id' => 6,
                'brand' => 'AllerFree',
                'manufacturer' => 'AllergyPharma',
                'image' => 'products/allergy_relief.jpg',
                'images' => json_encode(['products/allergy_relief.jpg']),
                'price' => 7.00,
                'discount' => 0,
                'stock' => 40,
                'availability' => 'in stock',
                'isNew' => false,
                'requiresPrescription' => false,
                'dosageForm' => 'Tablet',
                'strength' => '10mg',
                'ingredients' => 'Antihistamine',
                'usage' => 'Take 1 tablet daily',
                'expiryDate' => Carbon::now()->addYears(2),
                'sideEffects' => 'Drowsiness',
                'warning' => 'Avoid driving after taking',
                'storage' => 'Room temperature',
                'rating' => 4.1,
                'reviews' => 4,
                'reviewsList' => json_encode([]),
                'barcode' => '1234567891222',
                'batch_number' => 'BATCH006',
                'description' => 'Relieves allergy symptoms'
            ]
        ];

        foreach($products as $p){
            Product::create($p);
        }
    }
}